apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "posts.com"
    http:
      paths:
      - pathType: Prefix
        path: "/posts"
        backend:
          service:
            name: post-clusterip-srv
            port:
              number: 4000

  - host: "example.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: comments-clusterip-srv 
            port:
              number: 4001