apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: infophpadmin/post:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: post-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP
  ports:
    - name: post-clusterip-srv-ports
      protocol: TCP
      port: 4000
      targetPort: 4000
